CREATE DATABASE IF NOT EXISTS l5_connection;

CREATE TABLE IF NOT EXISTS ramais (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Name_username VARCHAR(20) NOT NULL,
    Host VARCHAR(50) NOT NULL,
    Dyn CHAR(1) NOT NULL,
    Nat CHAR(1) NOT NULL,
    ACL VARCHAR(10) NOT NULL,
    Port INT NOT NULL,
    Status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS filas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    ramais TEXT NOT NULL,
    status ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
